version: '3.4'

services:
  tickme:
    image: tickme:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44380
    ports:
      - target: 80
        published: 50080
        protocol: tcp
        mode: host
      - target: 443
        published: 44380
        protocol: tcp
        mode: host
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    deploy:
      mode: replicated
      replicas: 1
    entrypoint: dotnet TickMe.dll

  tickmepayments:
    image: tickmepayments:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44381
    ports:
      - "50081:80"
      - "44381:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    deploy:
      replicas: 3

  tickmetickets:
    image: tickmetickets:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44382
    ports:
      - "50082:80"
      - "44382:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    deploy:
      replicas: 1